wip: chain autoswap
BoltzExchange/boltz-client pull request #139
Opened 2024-04-21 16:00 UTC by jackstar12

2024-05-23 17:21 UTC, michael1011 commented on boltzrpc/autoswaprpc/autoswaprpc.proto
> +  Updates the lightning configuration completely or partially. Autoswap will reload the configuration after this call.
```suggestion
  Updates the lightning configuration entirely or partially. Autoswap will reload the configuration after this call.

```

2024-05-23 17:22 UTC, michael1011 commented on boltzrpc/autoswaprpc/autoswaprpc.proto
> +  Partially updates the onchain configuration. The autoswapper will reload the configuration after this call.
The lightning config can't be updated in it's entirety?

2024-05-23 21:49 UTC, jackstar12 commented on autoswap/autoswap.go
> +	if swapper.lnSwapper == nil || request.GetReset_() {
protobufs have a `Reset` method by default, so the `Reset` field is named `Reset_`

2024-06-06 15:26 UTC, kilrau requested changes
Addressing points of my previous review:
* Boltzd trying to refund all expired swaps seems fixed, this is gone:
![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/ff5b1b1f-843b-4f0a-ba85-35adbf36576b)
* concatenated chain swap config in `boltzcli autoswap setup` is nice, did a small rephrase
* currency question is gone, very nice
* some of the previous `autoswap status` display errors are fixed

Todo:
- [x] still can't find any way to manage `entities` like list/add/remove in `boltzcli`
- [x] chain swap status `Disabled` still not shown if it hasn't been configured
![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/0aeef9aa-3c69-41ab-9725-b002ded3a152) Once it's configured it shows as expected
![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/7959dcc9-2a88-4dd9-8a6d-b1fe2f9a03e8)
- [x] `boltzcli` should ask me " You already have an autoswap chain configuration. Do you want to reset it?" when I run `boltzcli autoswap setup chain` with an configuration, the same way `boltzcli autoswap setup` does.
![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/96d3386d-7b2a-4136-8e3c-89dd6fa85503)
- [x] still allows me to set below-min swap amount thresholds
![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/45b66466-7a1e-415b-9ffe-acc053e84f8c)

2024-06-25 11:02 UTC, kilrau commented
I configured `autoswap` previously, just didn't activate it and it was always recognized as such - now not anymore:
```
kilrau@K-Yoga:~$ boltzcli auto status
autoswap not configured
run autoswap setup to reset or initialize autoswap
kilrau@K-Yoga:~$ ls -la .boltz
total 384
drwx------  4 kilrau kilrau   4096 Jun 25 12:44 .
drwxr-x--- 38 kilrau kilrau   4096 Jun 25 12:50 ..
-rw-r--r--  1 kilrau kilrau    578 Jun  6 17:23 autoswap.toml
```
Went through the setup again and now it is recognized correctly. Didn't save the old `autoswap.toml` for comparison but looks like there was some breaking change?

2024-06-25 11:30 UTC, kilrau commented
`auto status` is looking really nice now, shall we add a "from" "to" statement for Lightning to?
```
$ boltzcli auto status
LN: Disabled
total balance (min 25.00%, max 75.00%)

Budget
 - From 2024-06-21T16:45:14+02:00 until 2024-06-28T16:45:14+02:00
 - Total: 100000 satoshis
 - Remaining: 100000 satoshis
Stats
 - Swaps: 0
 - Amount: 0 satoshis (avg 0 satoshis)
 - Fees: 0 satoshis (avg 0 satoshis)

Chain: Disabled
From wallet liquid (L-BTC) to wallet LND (BTC)

Budget
 - From 2024-06-20T16:50:15+02:00 until 2024-06-27T16:50:15+02:00
 - Total: 100000 satoshis
 - Remaining: 100000 satoshis
Stats
 - Swaps: 0
 - Amount: 0 satoshis (avg 0 satoshis)
 - Fees: 0 satoshis (avg 0 satoshis)
```

2024-06-25 15:55 UTC, kilrau requested changes
See previous comments

2024-06-25 20:48 UTC, jackstar12 commented
> Went through the setup again and now it is recognized correctly. Didn't save the old `autoswap.toml` for comparison but looks like there was some breaking change?

hm. I wrote a unit test which covers this case, will have another look

2024-06-25 21:03 UTC, jackstar12 commented
> I configured `autoswap` previously, just didn't activate it and it was always recognized as such - now not anymore:

It either was activated or you had a wallet which does not exist anymore. So its simply not valid anymore, which isn't displayed in the status error but it should be in the logs

2024-06-26 09:47 UTC, kilrau commented
> I configured `autoswap` previously, just didn't activate it and it was always recognized as such - now not anymore:
> 
> ```
> kilrau@K-Yoga:~$ boltzcli auto status
> autoswap not configured
> run autoswap setup to reset or initialize autoswap
> kilrau@K-Yoga:~$ ls -la .boltz
> total 384
> drwx------  4 kilrau kilrau   4096 Jun 25 12:44 .
> drwxr-x--- 38 kilrau kilrau   4096 Jun 25 12:50 ..
> -rw-r--r--  1 kilrau kilrau    578 Jun  6 17:23 autoswap.toml
> ```
> 
> Went through the setup again and now it is recognized correctly. Didn't save the old `autoswap.toml` for comparison but looks like there was some breaking change?

Yes there was: `Jun 25 12:23:30 K-Yoga boltzd[11365]: 2024-06-25 12:23:30.527 [WARN ] Could not load autoswap config: Could not decode autoswap config: proto: (line 1:72): unknown field "fromThreshold"`

Nothing to be done here.

2024-06-26 09:49 UTC, kilrau commented
> > Ehm is this hardcoded or does it fetch the current limit and just does 2xe for buffer purposes (which is fine as limits can change quite a bit after setup due to mainchain fee volatility)?
> > ![image](https://private-user-images.githubusercontent.com/19181985/342705286-575a1fce-d815-4a0c-8186-74f2f062fa35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDY2MDUsIm5iZiI6MTcxOTM0NjMwNSwicGF0aCI6Ii8xOTE4MTk4NS8zNDI3MDUyODYtNTc1YTFmY2UtZDgxNS00YTBjLTgxODYtNzRmMmYwNjJmYTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIwMTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4OTgyMjg5ZTM1ZmVjOGRkNGY3OWMxYTVmNDkxYTk5ZWU2NTBiMmMyNmEzYmNmYzMyZTkzMTRkZTkyM2JmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2oaqLQm590fxbMelxvIBW-GO_bWaeMMZ2DNJWjiR7A)
> 
> It fetches the limit and multiplies by 2 since it currently leaves half off the threshold in the wallet.

Ok, good! Can't come up with anything better, so nothing to be done here either :+1:

2024-06-26 09:49 UTC, kilrau commented
> > Went through the setup again and now it is recognized correctly. Didn't save the old `autoswap.toml` for comparison but looks like there was some breaking change?
> 
> hm. I wrote a unit test which covers this case, will have another look

All good, nothing to be done, see https://github.com/BoltzExchange/boltz-client/pull/139#issuecomment-2191273565

2024-06-27 10:15 UTC, kilrau commented
As per your suggestion @jackstar12  I manually changed the failed chain swaps state via `UPDATE chainSwaps SET state = 0 WHERE id = 'SVMG4Ad7M4K4';`, saved the db and started boltz client. Result:
```
Jun 27 12:05:57 K-Yoga boltzd[29878]: 2024-06-27 12:05:57.115 [INFO ] Opening database: /home/kilrau/.boltz/boltz.db
Jun 27 12:05:57 K-Yoga boltzd[29878]: 2024-06-27 12:05:57.116 [INFO ] database already at latest schema version: 10
Jun 27 12:05:57 K-Yoga boltzd[29878]: 2024-06-27 12:05:57.119 [ERROR] Could not get lightning info: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
Jun 27 12:05:57 K-Yoga boltzd[29878]: 2024-06-27 12:05:57.119 [INFO ] Retrying in 15 seconds
Jun 27 12:06:12 K-Yoga boltzd[29878]: 2024-06-27 12:06:12.120 [INFO ] Connected to lightning node  (0.18.0-beta commit=v0.18.0-beta): 020d9126d568b8f0605ed65eda28c4b843bb66282a0921d721f88b8a46cbd4e661
Jun 27 12:06:12 K-Yoga boltzd[29878]: 2024-06-27 12:06:12.120 [INFO ] Parsed chain: mainnet
Jun 27 12:06:12 K-Yoga boltzd[29878]: 2024-06-27 12:06:12.122 [INFO ] mempool.space API: https://mempool.space/api
Jun 27 12:06:12 K-Yoga boltzd[29878]: 2024-06-27 12:06:12.122 [INFO ] liquid.network API: https://liquid.network/api
Jun 27 12:06:12 K-Yoga boltzd[29878]: 2024-06-27 12:06:12.122 [INFO ] Using default Boltz endpoint for network mainnet: https://api.boltz.exchange
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.206 [INFO ] Connected to Boltz node LND (026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2)
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.206 [INFO ] Connected to Boltz node CLN (02d96eadea3d780104449aca5c93461ce67c1564e2e1d73225fa67dd3b997a6018)
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.207 [INFO ] Loaded TLS certificate and key
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.207 [INFO ] Enabling Macaroon authentication
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.208 [INFO ] Restarting all auto swappers because of wallet change
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.379 [INFO ] Starting nursery
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.379 [INFO ] Restarting all auto swappers because of wallet change
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.413 [INFO ] Connected to Boltz ws at wss://api.boltz.exchange/v2/ws
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Connecting to block BTC epoch stream
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Connecting to block L-BTC epoch stream
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Starting swap update listener
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Recovering pending Swaps
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Connecting to mempool websocket api: wss://liquid.network/api/v1/ws
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.414 [INFO ] Connecting to mempool websocket api: wss://mempool.space/api/v1/ws
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.416 [INFO ] Listening to events of Swaps: [SVMG4Ad7M4K4]
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.425 [INFO ] Starting lightning auto swapper
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.425 [INFO ] Starting chain auto swapper
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.428 [INFO ] Swap SVMG4Ad7M4K4 status update: transaction.refunded
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.433 [INFO ] Starting RPC server on: 127.0.0.1:9002
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.433 [INFO ] Starting REST server on: 127.0.0.1:9003
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.444 [INFO ] Chain Swap SVMG4Ad7M4K4 failed
Jun 27 12:06:13 K-Yoga boltzd[29878]: 2024-06-27 12:06:13.876 [INFO ] Using fee of 0.1 sat/vbyte for transaction
Jun 27 12:06:14 K-Yoga boltzd[29878]: 2024-06-27 12:06:14.477 [ERROR] Chain Swap SVMG4Ad7M4K4 error: broadcast: could not post tx, failed with code 400
Jun 27 12:06:14 K-Yoga boltzd[29878]: 2024-06-27 12:06:14.484 [ERROR] Chain Swap SVMG4Ad7M4K4 error: Could not refund Swap SVMG4Ad7M4K4: broadcast: could not post tx, failed with code 400
Jun 27 12:06:35 K-Yoga boltzd[29878]: 2024-06-27 12:06:35.936 [INFO ] Found 1 Swaps to refund at height 2918668
Jun 27 12:06:35 K-Yoga boltzd[29878]: 2024-06-27 12:06:35.947 [INFO ] Executing Swap recommendation: &{Amount:572298 FeeEstimate:5382 DismissedReasons:[]}
Jun 27 12:06:35 K-Yoga boltzd[29878]: 2024-06-27 12:06:35.947 [INFO ] Creating new chain swap
Jun 27 12:06:35 K-Yoga boltzd[29878]: 2024-06-27 12:06:35.959 [INFO ] Creating Chain Swap with preimage hash: 43fff862f877fc90318d05b2fb90bf9cd5c39d581ba82215ae79cb04485e4b3c
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.061 [INFO ] Verified redeem script and address of chainSwap arY8NRsM2mHK
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.064 [INFO ] Using fee of 0.1 sat/vbyte for transaction
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.109 [INFO ] Paying Chain Swap arY8NRsM2mHK with fee of 0.100000 sat/vbyte
Jun 27 12:06:36 K-Yoga boltzd[29878]: 36.623 ERROR - error: JsonError { message: "Electrum server error: \"sendrawtransaction RPC error: {\\\"code\\\":-26,\\\"message\\\":\\\"bad-txns-in-ne-out, value in != value out\\\"}\"", error: "id_unknown" }
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.636 [WARN ] RPC request failed: Electrum server error: "sendrawtransaction RPC error: {\"code\":-26,\"message\":\"bad-txns-in-ne-out, value in != value out\"}"
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.636 [ERROR] Could not act on swap recommendation: Electrum server error: "sendrawtransaction RPC error: {\"code\":-26,\"message\":\"bad-txns-in-ne-out, value in != value out\"}"
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.637 [ERROR] Chain Swap SVMG4Ad7M4K4 error: broadcast: could not post tx, failed with code 400
Jun 27 12:06:36 K-Yoga boltzd[29878]: 2024-06-27 12:06:36.637 [ERROR] Could not refund Swaps: broadcast: could not post tx, failed with code 400
Jun 27 12:07:36 K-Yoga boltzd[29878]: 2024-06-27 12:07:36.556 [INFO ] Found 1 Swaps to refund at height 2918669
Jun 27 12:07:36 K-Yoga boltzd[29878]: 2024-06-27 12:07:36.568 [INFO ] Skipping swap recommendation &{572298 5382 [pending swap]} because of [pending swap]
Jun 27 12:07:36 K-Yoga boltzd[29878]: 2024-06-27 12:07:36.684 [INFO ] Using fee of 0.1 sat/vbyte for transaction
Jun 27 12:07:37 K-Yoga boltzd[29878]: 2024-06-27 12:07:37.187 [ERROR] Chain Swap SVMG4Ad7M4K4 error: broadcast: could not post tx, failed with code 400
Jun 27 12:07:37 K-Yoga boltzd[29878]: 2024-06-27 12:07:37.187 [ERROR] Could not refund Swaps: broadcast: could not post tx, failed with code 400
Jun 27 12:08:36 K-Yoga boltzd[29878]: 2024-06-27 12:08:36.195 [INFO ] Found 1 Swaps to refund at height 2918670
Jun 27 12:08:36 K-Yoga boltzd[29878]: 2024-06-27 12:08:36.209 [INFO ] Skipping swap recommendation &{572298 5382 [pending swap]} because of [pending swap]
Jun 27 12:08:36 K-Yoga boltzd[29878]: 2024-06-27 12:08:36.321 [INFO ] Using fee of 0.1 sat/vbyte for transaction
Jun 27 12:08:36 K-Yoga boltzd[29878]: 2024-06-27 12:08:36.834 [ERROR] Chain Swap SVMG4Ad7M4K4 error: broadcast: could not post tx, failed with code 400
Jun 27 12:08:36 K-Yoga boltzd[29878]: 2024-06-27 12:08:36.834 [ERROR] Could not refund Swaps: broadcast: could not post tx, failed with code 400
```

Strangely, `boltzcli` shows the swap as refundable now:
```
$ boltzcli getinfo
{
  "version": "v2.0.2-daac977",
  "node": "LND",
  "network": "mainnet",
  "nodePubkey": "020d9126d568b8f0605ed65eda28c4b843bb66282a0921d721f88b8a46cbd4e661",
  "autoSwapStatus": "running",
  "blockHeights": {
    "btc": 849666,
    "liquid": 2918671
  },
  "refundableSwaps": [
    "SVMG4Ad7M4K4"
  ],
  "entity": {
    "id": "1",
    "name": "admin"
  }
```

```
Chain [...]

2024-06-27 11:50 UTC, kilrau commented
Refund was successful, boltz-client simply couldn't update the db when it was because I had it locked with another program in that moment. So that one is solved.

What's missing is fixing the failing new swap: gdk errored constructing the tx - swap in limbo state and nothing moves

Fix: always wait for gdk to be fully synced before attempting any swap & if gdk errors anyways abandon swap and try a new one

2024-06-29 09:13 UTC, kilrau commented
Missing as discussed is targeting 10k sats buffer for chain swaps (https://github.com/BoltzExchange/boltz-client/issues/140 will be shipped later)

2024-07-01 16:02 UTC, kilrau commented
No idea how I got into this config state, but definitely shouldn't crash.

```
$ boltzcli auto setup
? You already have an autoswap configuration. Do you want to reset it? Yes
? Which type of swaps should be executed? reverse
? Select wallet which should be used for swaps liquid
? How do you want to specify min/max balance values? percentage
? What is the maximum percentage of total capacity you want to keep in your channels? 20
? In which interval should the fee budget of the auto swapper be reset? (days) 7
? How many sats do you want to spend max on fees per budget interval? 50000

Config was saved successfully!
? Do you want to setup chain swaps as well? No
error reading from server: EOF
```


```
Jul 01 17:54:21 K-Yoga boltzd[5499]: 2024-07-01 17:54:21.398 [ERROR] Autoswap wallet configuration has become invalid: min balance must be smaller than max balance
Jul 01 17:54:24 K-Yoga boltzd[5499]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 01 17:54:24 K-Yoga boltzd[5499]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeef640]
Jul 01 17:54:24 K-Yoga boltzd[5499]: goroutine 177 [running]:
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/autoswap.(*LightningConfig).GetSwapRecommendations(0xc0008d75f0)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/autoswap/lightning.go:291 +0x40
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/rpcserver.(*routedAutoSwapServer).GetRecommendations(0xc0000b7b20, {0x15bde30, 0xc000370690}, 0xc0003700f0)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/rpcserver/autoswap.go:48 +0x85
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/boltzrpc/autoswaprpc._AutoSwap_GetRecommendations_Handler.func1({0x15bde30?, 0xc000370690?}, {0x122e4c0?, 0xc0003700f0?})
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/boltzrpc/autoswaprpc/autoswaprpc_grpc.pb.go:192 +0xcb
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/rpcserver.(*RpcServer).Init.(*Service).UnaryServerInterceptor.func4({0x15bde30?, 0xc000370090?}, {0x122e4c0, 0xc0003700f0}, 0xc000054f00?, 0xc00082a990)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/macaroons/interceptors.go:29 +0x6d
Jul 01 17:54:24 K-Yoga boltzd[5499]: google.golang.org/grpc.getChainUnaryHandler.func1({0x15bde30, 0xc000370090}, {0x122e4c0, 0xc0003700f0})
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1192 +0xb2
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/rpcserver.(*RpcServer).Init.(*routedBoltzServer).UnaryServerInterceptor.func2({0x15bde30, 0xc000370090}, {0x122e4c0, 0xc0003700f0}, 0xc00056e9e0?, 0xc000054f00)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/rpcserver/router.go:1493 +0x78
Jul 01 17:54:24 K-Yoga boltzd[5499]: google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1({0x15bde30, 0xc000370090}, {0x122e4c0, 0xc0003700f0}, 0xc00056e9e0, 0x78?)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1183 +0x85
Jul 01 17:54:24 K-Yoga boltzd[5499]: github.com/BoltzExchange/boltz-client/boltzrpc/autoswaprpc._AutoSwap_GetRecommendations_Handler({0x12b95c0, 0xc0000b7b20}, {0x15bde30, 0xc000370090}, 0xc0008cca00, 0xc00056e2c0)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/GitHub/boltz-client/boltzrpc/autoswaprpc/autoswaprpc_grpc.pb.go:194 +0x143
Jul 01 17:54:24 K-Yoga boltzd[5499]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006f8c00, {0x15bde30, 0xc000370000}, {0x15c6880, 0xc0000df520}, 0xc0007cd200, 0xc000576030, 0x1e3f7e0, 0x0)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1372 +0xdd1
Jul 01 17:54:24 K-Yoga boltzd[5499]: google.golang.org/grpc.(*Server).handleStream(0xc0006f8c00, {0x15c6880, 0xc0000df520}, 0xc0007cd200)
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1783 +0xfb8
Jul 01 17:54:24 K-Yoga boltzd[5499]: google.golang.org/grpc.(*Server).serveStreams.func2.1()
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1016 +0x59
Jul 01 17:54:24 K-Yoga boltzd[5499]: created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 198
Jul 01 17:54:24 K-Yoga boltzd[5499]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1027 +0x106
Jul 01 17:54:24 K-Yoga systemd[1]: boltzd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 01 17:54:24 K-Yoga systemd[1]: boltzd.service: Failed with result 'exit-code'.
```

Now it continues crashing:
```
Jul 01 17:55:24 K-Yoga boltzd[6417]: 2024-07-01 17:55:24.734 [ERROR] Autoswap wallet configuration has become invalid: min balance must be smaller than max balance
Jul 01 17:55:24 K-Yoga boltzd[6417]: 2024-07-01 17:55:24.735 [INFO ] Starting REST server on: 127.0.0.1:9003
Jul 01 17:55:24 K-Yoga boltzd[6417]: 2024-07-01 17:55:24.735 [INFO ] Starting RPC server on: 127.0.0.1:9002
Jul 01 17:57:36 K-Yoga boltzd[6417]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 01 17:57:36 K-Yoga boltzd[6417]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeef640]
Jul 01 17:57:36 K-Yoga boltzd[6417]: goroutine 131 [running]:
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/autoswap.(*LightningConfig).GetSwapRecommendations(0xc00092d8c0)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-client/autoswap/lightning.go:291 +0x40
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/rpcserver.(*routedAutoSwapServer).GetRecommendations(0xc0002fc0a0, {0x15bde30, 0xc00070e780}, 0xc00070e3c0)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-client/rpcserver/autoswap.go:48 +0x85
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/boltzrpc/autoswaprpc._AutoSwap_GetRecommendations_Handler.func1({0x15bde30?, 0xc00070e780?}, {0x122e4c0?, 0xc00070e3c0?})
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-client/boltzrpc/autoswaprpc/autoswaprpc_grpc.pb.go:192 +0xcb
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/rpcserver.(*RpcServer).Init.(*Service).UnaryServerInterceptor.func4({0x15bde30?, 0xc00070e390?}, {0x122e4c0, 0xc00070e3c0}, 0xc000394300?, 0xc00072e1b0)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-client/macaroons/interceptors.go:29 +0x6d
Jul 01 17:57:36 K-Yoga boltzd[6417]: google.golang.org/grpc.getChainUnaryHandler.func1({0x15bde30, 0xc00070e390}, {0x122e4c0, 0xc00070e3c0})
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1192 +0xb2
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/rpcserver.(*RpcServer).Init.(*routedBoltzServer).UnaryServerInterceptor.func2({0x15bde30, 0xc00070e390}, {0x122e4c0, 0xc00070e3c0}, 0xc0007720c0?, 0xc000394300)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-client/rpcserver/router.go:1493 +0x78
Jul 01 17:57:36 K-Yoga boltzd[6417]: google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1({0x15bde30, 0xc00070e390}, {0x122e4c0, 0xc00070e3c0}, 0xc0007720c0, 0x78?)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1183 +0x85
Jul 01 17:57:36 K-Yoga boltzd[6417]: github.com/BoltzExchange/boltz-client/boltzrpc/autoswaprpc._AutoSwap_GetRecommendations_Handler({0x12b95c0, 0xc0002fc0a0}, {0x15bde30, 0xc00070e390}, 0xc0008d4080, 0xc0002fcec0)
Jul 01 17:57:36 K-Yoga boltzd[6417]:         /home/kilrau/GitHub/boltz-clien [...]

2024-07-05 17:21 UTC, jackstar12 commented on onchain/onchain.go
> +	}
Takes too long if you want to mock a test case where it actually isn't confirmed but is expected to

2024-07-08 10:00 UTC, kilrau commented on docs/autoswap.md
> +The same happens if the inbound balance goes below the configured `inboundBalance` or `inboundBalancePercent`.
```suggestion
The same way, autoswap will create reverse swaps when the inbound balance goes below the configured `inboundBalance` or `inboundBalancePercent`.
```

2024-07-08 10:02 UTC, kilrau commented on docs/autoswap.md
> +If only one of the two thresholds is configured, the balance target will always be the full channel capacity.
```suggestion
If `inboundBalance` is configured as threshold, the rebalancing target will always be the full channel capacity.
```

2024-07-08 10:04 UTC, kilrau commented on docs/autoswap.md
> +- Result: A 400k sats reverse swap since the inbound balance is below the set threshold.
```suggestion
- Result: A 400k sats reverse swap will be executed, to bring back inbound inbound balance to the full 500k sats channel capacity.```

2024-07-08 13:13 UTC, merged